spring.application.name=ClientDesk

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

jwt.secret = ${JWT_SECRET}
jwt.expiration = ${JWT_EXPIRATION:86400000}


app.frontend.url=${FRONTEND_URL:http://localhost:5173}
server.port=${PORT:8080}

logging.level.root =INFO
logging.level.com.project.ClientDesk=INFO
logging.file.name=logs/clientdesk.log